version: 3

tasks:
  install:
    cmds:
      - python3 setup.py install

  watch:
    cmds:
      - ls sce/*.py | entr -cp python3 -m sce

  venv_deactivate:
    ignore_error: true
    cmds:
      - deactivate

  venv_activate:
    cmds:
      - python3 -m venv venv 
      - source venv/bin/activate
      - pip3 install .

  venv:
    cmds:
      - task: venv_deactivate
      - task: venv_activate
  
  poet:
    cmds:
      - pip3 install homebrew-pypi-poet 
      - poet -f sce

  run:
    cmds:
      - |
        python3 -m sce \
          --token $(op item get "Slack Service Token" --field password) \
          --organization "codecentric AG" \
          --implied_phone_region "DE" \
          --output ~/Desktop/contacts.vcf

